version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  website:
    build: ./website
    ports:
      - "3000:3000"
    volumes:
      - ./website:/app
    command: npm run dev